"""
modules/stocks/stock_execution_event_service.py

Sprint 5.3
===========

Institutional Execution Event Framework

This service is responsible ONLY for recording immutable execution
events generated by the trading engine.

It is intentionally isolated from:

    - Recommendation generation
    - Portfolio analytics
    - Attribution
    - AI review
    - Dashboard rendering

Those systems consume these events but never create them.

Execution Flow
--------------

Trading UI
      │
      ▼
StockTradingService
      │
      ▼
OrderService
      │
      ▼
StockExecutionEventService
      │
      ▼
stock_execution_events table
      │
      ├── Attribution
      ├── AI Review
      ├── Compliance
      ├── Audit
      ├── Performance Analytics
      └── Executive Dashboards

Every execution event is immutable.
"""

from __future__ import annotations

import json
import logging
import uuid

from dataclasses import dataclass, asdict
from datetime import UTC, datetime
from enum import Enum
from typing import Any, Dict, Optional

from sqlalchemy import text
from sqlalchemy.exc import SQLAlchemyError

logger = logging.getLogger(__name__)


# ==========================================================
# Execution Event Types
# ==========================================================


class ExecutionEventType(str, Enum):

    ORDER_CREATED = "ORDER_CREATED"

    ORDER_SUBMITTED = "ORDER_SUBMITTED"

    ORDER_ACCEPTED = "ORDER_ACCEPTED"

    ORDER_FILLED = "ORDER_FILLED"

    ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"

    ORDER_CANCELLED = "ORDER_CANCELLED"

    ORDER_REJECTED = "ORDER_REJECTED"

    POSITION_OPENED = "POSITION_OPENED"

    POSITION_MODIFIED = "POSITION_MODIFIED"

    POSITION_PARTIALLY_CLOSED = "POSITION_PARTIALLY_CLOSED"

    POSITION_CLOSED = "POSITION_CLOSED"

    POSITION_REVERSED = "POSITION_REVERSED"

    STOP_LOSS_TRIGGERED = "STOP_LOSS_TRIGGERED"

    TAKE_PROFIT_TRIGGERED = "TAKE_PROFIT_TRIGGERED"

    FLATTEN_PORTFOLIO = "FLATTEN_PORTFOLIO"


# ==========================================================
# Event Record
# ==========================================================


@dataclass(slots=True)
class ExecutionEvent:

    event_id: str

    event_type: str

    timestamp: datetime

    tenant_id: Optional[str] = None

    portfolio_id: Optional[str] = None

    user_id: Optional[str] = None

    recommendation_id: Optional[int] = None

    order_id: Optional[int] = None

    broker_order_id: Optional[str] = None

    position_id: Optional[int] = None

    symbol: Optional[str] = None

    side: Optional[str] = None

    quantity: Optional[float] = None

    price: Optional[float] = None

    broker: Optional[str] = None

    status: Optional[str] = None

    metadata: Dict[str, Any] | None = None


# ==========================================================
# Event Service
# ==========================================================


class StockExecutionEventService:
    """
    Immutable execution event recorder.

    This service NEVER performs trading.

    It ONLY records what already happened.

    Events are append-only.

    Existing events are never updated.
    """

    def __init__(
        self,
        db,
    ):

        self.db = db

        self._ensure_tables()

    # ======================================================
    # Bootstrap
    # ======================================================

    def _ensure_tables(self) -> None:
        """
        Ensures execution event storage exists.

        Full DDL implemented in Part 2.
        """

        try:

            self.db.execute(
                text(
                    """
                    SELECT 1
                    """
                )
            )

        except Exception:

            logger.exception(
                "Unable to initialize execution event service."
            )

    # ======================================================
    # Helpers
    # ======================================================

    @staticmethod
    def _new_event_id() -> str:

        return str(uuid.uuid4())

    @staticmethod
    def _utc_now() -> datetime:

        return datetime.now(UTC)

    @staticmethod
    def _safe_json(
        value: Any,
    ) -> str:

        try:

            return json.dumps(
                value,
                default=str,
            )

        except Exception:

            return "{}"

    @staticmethod
    def _clean_metadata(
        metadata: Optional[Dict[str, Any]],
    ) -> Dict[str, Any]:

        if metadata is None:

            return {}

        cleaned: Dict[str, Any] = {}

        for key, value in metadata.items():

            try:

                json.dumps(
                    value,
                    default=str,
                )

                cleaned[key] = value

            except Exception:

                cleaned[key] = str(value)

        return cleaned

    # ======================================================
    # Internal Recording API
    # ======================================================

    def _record_event(
        self,
        *,
        event_type: ExecutionEventType,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Core execution recorder.

        Persistence implementation added
        in Part 2.
        """

        return ExecutionEvent(

            event_id=self._new_event_id(),

            event_type=event_type.value,

            timestamp=self._utc_now(),

            tenant_id=getattr(order, "tenant_id", None),

            portfolio_id=getattr(order, "portfolio_id", None),

            user_id=getattr(order, "user_id", None),

            recommendation_id=getattr(
                order,
                "recommendation_id",
                None,
            ),

            order_id=getattr(
                order,
                "id",
                None,
            ),

            broker_order_id=getattr(
                order,
                "broker_order_id",
                None,
            ),

            position_id=getattr(
                order,
                "position_id",
                None,
            ),

            symbol=getattr(
                order,
                "symbol",
                None,
            ),

            side=getattr(
                order,
                "side",
                None,
            ),

            quantity=getattr(
                order,
                "filled_qty",
                getattr(
                    order,
                    "qty",
                    None,
                ),
            ),

            price=getattr(
                order,
                "avg_fill_price",
                None,
            ),

            broker=getattr(
                order,
                "broker",
                None,
            ),

            status=getattr(
                order,
                "status",
                None,
            ),

            metadata=self._clean_metadata(
                metadata,
            ),
        )

    # ======================================================
    # Table Bootstrap
    # ======================================================

    def _ensure_tables(self) -> None:
        """
        Create execution event storage if it does not exist.
        """

        if self.db is None:
            return

        try:

            self.db.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS stock_execution_events (

                        event_id              VARCHAR(36) PRIMARY KEY,

                        event_type            VARCHAR(80) NOT NULL,

                        event_timestamp       TIMESTAMP NOT NULL,

                        tenant_id             VARCHAR(100),

                        portfolio_id          VARCHAR(100),

                        user_id               VARCHAR(100),

                        recommendation_id     INTEGER,

                        order_id              BIGINT,

                        broker_order_id       VARCHAR(100),

                        position_id           BIGINT,

                        symbol                VARCHAR(25),

                        side                  VARCHAR(20),

                        quantity              DOUBLE PRECISION,

                        price                 DOUBLE PRECISION,

                        broker                VARCHAR(100),

                        status                VARCHAR(50),

                        metadata              TEXT
                    )
                    """
                )
            )

            self.db.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_execution_events_timestamp
                    ON stock_execution_events(event_timestamp)
                    """
                )
            )

            self.db.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_execution_events_symbol
                    ON stock_execution_events(symbol)
                    """
                )
            )

            self.db.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_execution_events_order
                    ON stock_execution_events(order_id)
                    """
                )
            )

            self.db.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_execution_events_position
                    ON stock_execution_events(position_id)
                    """
                )
            )

            self.db.execute(
                text(
                    """
                    CREATE INDEX IF NOT EXISTS idx_execution_events_portfolio
                    ON stock_execution_events(portfolio_id)
                    """
                )
            )

            self.db.commit()

        except SQLAlchemyError:

            logger.exception(
                "Unable to initialize stock_execution_events table."
            )

            try:
                self.db.rollback()
            except Exception:
                pass

    # ======================================================
    # Persistence
    # ======================================================

    def _persist_event(
            self,
            event: ExecutionEvent,
    ) -> None:

        if self.db is None:
            return

        try:

            self.db.execute(

                text(
                    """
                    INSERT INTO stock_execution_events (

                        event_id,
                        event_type,
                        event_timestamp,

                        tenant_id,
                        portfolio_id,
                        user_id,

                        recommendation_id,

                        order_id,
                        broker_order_id,
                        position_id,

                        symbol,
                        side,

                        quantity,
                        price,

                        broker,
                        status,

                        metadata

                    )
                    VALUES (

                        :event_id,
                        :event_type,
                        :event_timestamp,

                        :tenant_id,
                        :portfolio_id,
                        :user_id,

                        :recommendation_id,

                        :order_id,
                        :broker_order_id,
                        :position_id,

                        :symbol,
                        :side,

                        :quantity,
                        :price,

                        :broker,
                        :status,

                        :metadata
                    )
                    """
                ),

                {

                    "event_id":
                        event.event_id,

                    "event_type":
                        event.event_type,

                    "event_timestamp":
                        event.timestamp,

                    "tenant_id":
                        event.tenant_id,

                    "portfolio_id":
                        event.portfolio_id,

                    "user_id":
                        event.user_id,

                    "recommendation_id":
                        event.recommendation_id,

                    "order_id":
                        event.order_id,

                    "broker_order_id":
                        event.broker_order_id,

                    "position_id":
                        event.position_id,

                    "symbol":
                        event.symbol,

                    "side":
                        event.side,

                    "quantity":
                        event.quantity,

                    "price":
                        event.price,

                    "broker":
                        event.broker,

                    "status":
                        event.status,

                    "metadata":
                        self._safe_json(
                            event.metadata,
                        ),
                },
            )

            self.db.commit()

        except SQLAlchemyError:

            logger.exception(
                "Failed to persist execution event."
            )

            try:
                self.db.rollback()
            except Exception:
                pass

    # ======================================================
    # Internal Recording API
    # ======================================================

    def _record_event(
            self,
            *,
            event_type: ExecutionEventType,
            order: Any,
            metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Creates and persists an immutable execution event.
        """

        event = ExecutionEvent(

            event_id=self._new_event_id(),

            event_type=event_type.value,

            timestamp=self._utc_now(),

            tenant_id=getattr(order, "tenant_id", None),

            portfolio_id=getattr(order, "portfolio_id", None),

            user_id=getattr(order, "user_id", None),

            recommendation_id=getattr(
                order,
                "recommendation_id",
                None,
            ),

            order_id=getattr(
                order,
                "id",
                None,
            ),

            broker_order_id=getattr(
                order,
                "broker_order_id",
                None,
            ),

            position_id=getattr(
                order,
                "position_id",
                None,
            ),

            symbol=getattr(
                order,
                "symbol",
                None,
            ),

            side=getattr(
                order,
                "side",
                None,
            ),

            quantity=getattr(
                order,
                "filled_qty",
                getattr(
                    order,
                    "qty",
                    None,
                ),
            ),

            price=getattr(
                order,
                "avg_fill_price",
                None,
            ),

            broker=getattr(
                order,
                "broker",
                None,
            ),

            status=getattr(
                order,
                "status",
                None,
            ),

            metadata=self._clean_metadata(
                metadata,
            ),
        )

        self._persist_event(event)

        logger.info(
            "Execution Event Recorded | %s | %s | %s",
            event.event_type,
            event.symbol,
            event.order_id,
        )

        return event

    # ======================================================
    # Order Events
    # ======================================================

    def order_created(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        A new order has been created inside the application.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_CREATED,
            order=order,
            metadata=metadata,
        )

    def order_submitted(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Order has been submitted to the broker.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_SUBMITTED,
            order=order,
            metadata=metadata,
        )

    def order_accepted(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Broker acknowledged the order.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_ACCEPTED,
            order=order,
            metadata=metadata,
        )

    def order_filled(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Order completely filled.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_FILLED,
            order=order,
            metadata=metadata,
        )

    def order_partially_filled(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Order partially filled.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_PARTIALLY_FILLED,
            order=order,
            metadata=metadata,
        )

    def order_cancelled(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Order cancelled.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_CANCELLED,
            order=order,
            metadata=metadata,
        )

    def order_rejected(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Broker rejected the order.
        """

        return self._record_event(
            event_type=ExecutionEventType.ORDER_REJECTED,
            order=order,
            metadata=metadata,
        )

    # ======================================================
    # Position Events
    # ======================================================

    def position_opened(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        New position established.
        """

        return self._record_event(
            event_type=ExecutionEventType.POSITION_OPENED,
            order=order,
            metadata=metadata,
        )

    def position_modified(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Position size or attributes changed.
        """

        return self._record_event(
            event_type=ExecutionEventType.POSITION_MODIFIED,
            order=order,
            metadata=metadata,
        )

    def position_partially_closed(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Partial position exit.
        """

        return self._record_event(
            event_type=ExecutionEventType.POSITION_PARTIALLY_CLOSED,
            order=order,
            metadata=metadata,
        )

    def position_closed(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Position completely closed.
        """

        return self._record_event(
            event_type=ExecutionEventType.POSITION_CLOSED,
            order=order,
            metadata=metadata,
        )

    def position_reversed(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Existing position reversed.
        """

        return self._record_event(
            event_type=ExecutionEventType.POSITION_REVERSED,
            order=order,
            metadata=metadata,
        )

    # ======================================================
    # Risk Events
    # ======================================================

    def stop_loss_triggered(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Stop-loss execution.
        """

        return self._record_event(
            event_type=ExecutionEventType.STOP_LOSS_TRIGGERED,
            order=order,
            metadata=metadata,
        )

    def take_profit_triggered(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Take-profit execution.
        """

        return self._record_event(
            event_type=ExecutionEventType.TAKE_PROFIT_TRIGGERED,
            order=order,
            metadata=metadata,
        )

    def flatten_portfolio(
        self,
        order: Any,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExecutionEvent:
        """
        Entire portfolio flattened.
        """

        return self._record_event(
            event_type=ExecutionEventType.FLATTEN_PORTFOLIO,
            order=order,
            metadata=metadata,
        )

    # ======================================================
    # Query API
    # ======================================================

    def get_events(
            self,
            *,
            portfolio_id: Optional[str] = None,
            order_id: Optional[int] = None,
            position_id: Optional[int] = None,
            symbol: Optional[str] = None,
            event_type: Optional[str] = None,
            limit: int = 250,
    ) -> list[dict]:
        """
        Return execution events using optional filters.
        """

        if self.db is None:
            return []

        sql = """
            SELECT *
            FROM stock_execution_events
            WHERE 1=1
        """

        params: Dict[str, Any] = {}

        if portfolio_id:
            sql += " AND portfolio_id = :portfolio_id"
            params["portfolio_id"] = portfolio_id

        if order_id is not None:
            sql += " AND order_id = :order_id"
            params["order_id"] = order_id

        if position_id is not None:
            sql += " AND position_id = :position_id"
            params["position_id"] = position_id

        if symbol:
            sql += " AND UPPER(symbol) = :symbol"
            params["symbol"] = symbol.upper()

        if event_type:
            sql += " AND event_type = :event_type"
            params["event_type"] = event_type

        sql += """
            ORDER BY event_timestamp DESC
            LIMIT :limit
        """

        params["limit"] = limit

        try:

            rows = (
                self.db.execute(
                    text(sql),
                    params,
                )
                .mappings()
                .all()
            )

            return [dict(r) for r in rows]

        except SQLAlchemyError:

            logger.exception(
                "Unable to load execution events."
            )

            return []

    # ======================================================
    # Event Statistics
    # ======================================================

    def get_statistics(
            self,
            *,
            portfolio_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Build high-level execution statistics.
        """

        events = self.get_events(
            portfolio_id=portfolio_id,
            limit=100000,
        )

        stats = {

            "total_events": len(events),

            "orders_created": 0,

            "orders_submitted": 0,

            "orders_filled": 0,

            "orders_cancelled": 0,

            "orders_rejected": 0,

            "positions_opened": 0,

            "positions_closed": 0,

            "stop_losses": 0,

            "take_profits": 0,
        }

        for event in events:

            event_type = event.get("event_type")

            if event_type == ExecutionEventType.ORDER_CREATED.value:
                stats["orders_created"] += 1

            elif event_type == ExecutionEventType.ORDER_SUBMITTED.value:
                stats["orders_submitted"] += 1

            elif event_type == ExecutionEventType.ORDER_FILLED.value:
                stats["orders_filled"] += 1

            elif event_type == ExecutionEventType.ORDER_CANCELLED.value:
                stats["orders_cancelled"] += 1

            elif event_type == ExecutionEventType.ORDER_REJECTED.value:
                stats["orders_rejected"] += 1

            elif event_type == ExecutionEventType.POSITION_OPENED.value:
                stats["positions_opened"] += 1

            elif event_type == ExecutionEventType.POSITION_CLOSED.value:
                stats["positions_closed"] += 1

            elif event_type == ExecutionEventType.STOP_LOSS_TRIGGERED.value:
                stats["stop_losses"] += 1

            elif event_type == ExecutionEventType.TAKE_PROFIT_TRIGGERED.value:
                stats["take_profits"] += 1

        return stats

    # ======================================================
    # Export API
    # ======================================================

    def export_events(
            self,
            *,
            portfolio_id: Optional[str] = None,
    ) -> list[dict]:
        """
        Export execution events.

        Future versions can serialize directly
        to CSV, Parquet, JSON, or audit packages.
        """

        return self.get_events(
            portfolio_id=portfolio_id,
            limit=1_000_000,
        )

    # ======================================================
    # Maintenance
    # ======================================================

    def delete_events_for_portfolio(
            self,
            portfolio_id: str,
    ) -> int:
        """
        Administrative helper.

        Normally execution events should remain
        immutable and permanent.

        This exists only for development,
        testing, or tenant cleanup.
        """

        if self.db is None:
            return 0

        try:

            result = self.db.execute(

                text(
                    """
                    DELETE
                    FROM stock_execution_events
                    WHERE portfolio_id = :portfolio_id
                    """
                ),

                {
                    "portfolio_id": portfolio_id,
                },
            )

            self.db.commit()

            return int(result.rowcount or 0)

        except SQLAlchemyError:

            logger.exception(
                "Unable to delete execution events."
            )

            try:
                self.db.rollback()
            except Exception:
                pass

            return 0

# ==========================================================
# Factory
# ==========================================================

_execution_event_service: Optional[
    StockExecutionEventService
] = None

def get_stock_execution_event_service(
        db,
) -> StockExecutionEventService:
    """
    Shared factory used by StockTradingService
    and future execution consumers.
    """

    return StockExecutionEventService(db)