"""
modules/forex/forex_monte_carlo.py

Real Monte Carlo simulation. Bootstrap-resamples (with replacement) the
actual trade returns produced by forex_strategy_backtester on live daily
closes, replacing the previous hardcoded
{"probability_profit": 0.61, "p5_drawdown_pct": 14.2, "p95_return_pct": 28.6}
stub, which ignored the strategy and the `runs` parameter entirely and
never changed no matter what was passed in.
"""

from __future__ import annotations

import random
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from modules.forex.forex_strategy_backtester import (
    DEFAULT_LOOKBACK_DAYS,
    DEFAULT_PAIR,
    _fetch_price_series,
    _rolling_factor_score,
    run_single_backtest,
)

MIN_TRADES_FOR_SIMULATION = 5
DEFAULT_RUNS = 1000


def _percentile(sorted_values, pct: float) -> Optional[float]:
    if not sorted_values:
        return None
    k = (len(sorted_values) - 1) * pct
    f = int(k)
    c = min(f + 1, len(sorted_values) - 1)
    if f == c:
        return sorted_values[f]
    return sorted_values[f] + (sorted_values[c] - sorted_values[f]) * (k - f)


class ForexMonteCarlo:
    def __init__(self, db: Optional[Any] = None):
        self.db = db

    def simulate(
        self,
        strategy: Dict[str, Any],
        pair: Optional[str] = None,
        lookback_days: int = DEFAULT_LOOKBACK_DAYS,
        runs: int = DEFAULT_RUNS,
    ) -> Dict[str, Any]:
        name = strategy.get("name", "FX Strategy")
        pair = pair or strategy.get("pair") or DEFAULT_PAIR
        runs = int(runs) if runs else DEFAULT_RUNS

        try:
            closes = _fetch_price_series(pair, lookback_days)
        except Exception as exc:
            return {"status": "ERROR", "strategy": name, "pair": pair, "error": str(exc)}

        if closes is None or len(closes) < 40:
            return {
                "status": "NO_DATA",
                "strategy": name,
                "pair": pair,
                "message": "Not enough live historical data to simulate yet.",
            }

        scores = _rolling_factor_score(closes)
        run_result = run_single_backtest(strategy, closes, scores)
        trade_returns = [t["return_pct"] / 100.0 for t in run_result["trades"]]

        if len(trade_returns) < MIN_TRADES_FOR_SIMULATION:
            return {
                "status": "INSUFFICIENT_TRADES",
                "strategy": name,
                "pair": pair,
                "trades_available": len(trade_returns),
                "message": (
                    f"Only {len(trade_returns)} real trade(s) were generated by the "
                    f"backtest -- too few to bootstrap a meaningful Monte Carlo "
                    f"distribution (minimum {MIN_TRADES_FOR_SIMULATION})."
                ),
            }

        total_returns = []
        max_drawdowns = []

        for _ in range(runs):
            sample = random.choices(trade_returns, k=len(trade_returns))
            equity = 1.0
            peak = 1.0
            max_dd = 0.0
            for r in sample:
                equity *= (1.0 + r)
                if equity > peak:
                    peak = equity
                dd = (equity / peak - 1.0) if peak > 0 else 0.0
                if dd < max_dd:
                    max_dd = dd
            total_returns.append((equity - 1.0) * 100.0)
            max_drawdowns.append(abs(max_dd) * 100.0)

        total_returns.sort()
        max_drawdowns.sort()

        probability_profit = round(sum(1 for r in total_returns if r > 0) / len(total_returns), 4)
        # "p5" framed as a risk/VaR-style bad-case number: the 95th percentile
        # of simulated drawdowns (i.e. only 5% of simulated paths drew down more).
        p5_drawdown_pct = round(_percentile(max_drawdowns, 0.95), 2)
        p95_return_pct = round(_percentile(total_returns, 0.95), 2)

        return {
            "status": "READY",
            "strategy": name,
            "pair": pair,
            "runs": runs,
            "trades_used": len(trade_returns),
            "probability_profit": probability_profit,
            "p5_drawdown_pct": p5_drawdown_pct,
            "p95_return_pct": p95_return_pct,
            "methodology": (
                "Bootstrap resampling (with replacement) of the real trade "
                "returns produced by forex_strategy_backtester on live daily "
                "closes -- not a parametric or synthetic simulation. "
                "p5_drawdown_pct is the 95th percentile of simulated max "
                "drawdowns (a bad-case outcome); p95_return_pct is the 95th "
                "percentile of simulated total returns (a good-case outcome)."
            ),
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }


_MC = None


def get_forex_monte_carlo(db: Optional[Any] = None) -> ForexMonteCarlo:
    global _MC
    if _MC is None or (db is not None and _MC.db is None):
        _MC = ForexMonteCarlo(db=db)
    return _MC